[settings]
#dimensions=2
arrangement_file="settings/zigzag200.csv"
#arrangement_file="./settings/thousand.csv"
#arrangement_file="./settings/tenthousand.csv"
io_pin=10
#number_lights=200
rows=[29, 29, 32, 29, 32, 28, 20]
url="http://127.0.0.1:5000"

[test]
test_mode=true
sphere_size=0.01
camera_position=[0.5, 0.5, 2.0]
dimension_mask=[0, 1, 2]

[performance]
number_children_for_division=75
