[settings]
dimensions=2
arrangement_file="settings/positions2d.csv"
io_pin=10
number_lights=100
rows=[20, 20, 20, 20, 20]

[test]
test_mode=true
sphere_size=0.02
camera_position=[0.5, 0.5, 2.0]
dimension_mask=[0, 1, 2]
