[settings]
dimensions=2
arrangement_file="settings/zigzag200.csv"
io_pin=10
number_lights=200
rows=[29, 29, 32, 29, 32, 28, 20]

[test]
test_mode=true
sphere_size=0.01
camera_position=[0.5, 0.5, 2.0]
dimension_mask=[0, 1, 2]
